config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  post 'keywords' => 'keywords#import'
  get 'select_date' => 'dashboard#select_date'
  get 'import' => 'dashboard#get_import'

  

end

app/views/shared/_ctr_group.html.erb
<div class="table-responsive">
           <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Position Group</th>
                    <th>CTR</th>
                    <th>CTR from previous period</th>
                    <th>Comparison</th>
                </tr>
            </thead>
            <tbody>
            <% ctr_group(@keywords_1).each_with_index do |val, index| %>
              <% i = index+1 %>
              <% i = 9 if (i) > 8%>
              <tr>
                    <!-- data 1 -->
                    <td><%= index+1 %></td>
                    <td class="td<%= i %>"><%= top_keyword(val[1], "ctr")%> %</td>
                    <td><%= second_period(val[0], @keywords_2, "ctr")%> %</td>
                    <td>+ <%= compare_result(top_keyword(val[1], "ctr"), second_period(val[0], @keywords_2, "ctr"))%></td>
                </tr>
            <% end %>
                </tbody>
              </table>
          </div>

app/views/shared/_improved_rankings.html.erb
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th></th>
                <th>Visibility (current)</th>
                <th>Traffic</th>
                <th>Average CTR</th>
                <th>Average Position</th>
            </tr>
        </thead>
        <tbody>
            <% improved_rankings(@keywords_1).each_with_index do |val, index| %>
              <% imp, clicks, ctr, avg_position = collect_datas(val[1]) %>
              <% s_imp, s_clicks, s_ctr, s_avg_position = s_collect_datas(val[0], @keywords_2) %>
              <tr>
                <td><%= val[0] %></td>
                <td><%= imp %> <br> Impressions <br> +<%= s_imp %> <br> ( <%= compare_result(imp, s_imp) %> )</td>
                <td><%= clicks %> <br> Clicks <br> +<%= s_clicks %> <br> ( <%= compare_result(clicks, s_clicks)%> )</td>
                <td><%= ctr %> <br> +<%= s_ctr %> <br> ( <%= compare_result(ctr, s_ctr)%> )</td>
                <td><%= avg_position %> <br> +<%= s_avg_position %><br> (<%= compare_result(avg_position, s_avg_position)%>)</td>
              </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/shared/_lost_rankings.html.erb
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th></th>
                <th>Visibility (current)</th>
                <th>Traffic</th>
                <th>Average CTR</th>
                <th>Average Position</th>
            </tr>
        </thead>
        <tbody>
            <% lost_rankings(@keywords_1).each_with_index do |val, index| %>
              <% imp, clicks, ctr, avg_position = collect_datas(val[1]) %>
              <% s_imp, s_clicks, s_ctr, s_avg_position = s_collect_datas(val[0], @keywords_2) %>
              <tr>
                <td><%= val[0] %></td>
                <td><%= imp %> <br> Impressions <br> +<%= s_imp %> <br> ( <%= compare_result(imp, s_imp) %> )</td>
                <td><%= clicks %> <br> Clicks <br> +<%= s_clicks %> <br> ( <%= compare_result(clicks, s_clicks)%> )</td>
                <td><%= ctr %> <br> +<%= s_ctr %> <br> ( <%= compare_result(ctr, s_ctr)%> )</td>
                <td><%= avg_position %> <br> +<%= s_avg_position %><br> (<%= compare_result(avg_position, s_avg_position)%>)</td>
              </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/shared/_navbar.html.erb
 <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Keywords", root_path, class: "navbar-brand" %>
        </div>
        <div class="pull-right change-date"><%= link_to 'Change Date', :back , class: "back-page btn btn-default hide", "data-no-turbolink" => true %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path, "data-no-turbolink" => true %></li>
            <li><%= link_to "Import", import_path, "data-no-turbolink" => true %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <script>
      
    </script>

app/views/shared/_table_overview.html.erb
<div class="table-responsive">
   <table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th></th>
            <th>Total Number of Keywords</th>
            <th>Visibility (current)</th>
            <th>Traffic</th>
            <th>Average CTR</th>
            <th>Average Position</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <!-- title 1 -->
            <th>Overall</th>
            <td>
                <%= overall_tnk(@keywords_1, @keywords_2) %><br>
                +<%= new_queries_tnk(@keywords_1, @keywords_2) %>
            </td>
            <td>
                <%= overall_visbl(@keywords_1, @keywords_2) %><br>
                Impressions<br>
                +<%= visibility_new_true(@keywords_1, @keywords_2) %><br>
                (<%= overall_visibility_percentage(@keywords_1, @keywords_2) %>)
            </td>
            <td>
                <%= overall_traffic(@keywords_1, @keywords_2) %><br>
                Clicks<br>
                +<%= traffic_new_true(@keywords_1, @keywords_2) %><br>
                (<%= overall_traffic_percentage(@keywords_1, @keywords_2) %>)
            </td>
            <td>
                <%= number_with_precision(overall_avg_ctr(@keywords_1, @keywords_2), :precision => 2) %><br>
                +<%= number_with_precision(avg_ctr_new_true(@keywords_1, @keywords_2), :precision => 2)%><br>
                (<%= overall_avg_CTR_percentage(@keywords_1, @keywords_2)%>)
            </td>
            <td>
                <%= number_with_precision(overall_avg_position(@keywords_1, @keywords_2), :precision => 2) %><br>
                +<%= number_with_precision(avg_position_new_true(@keywords_1, @keywords_2), :precision => 2)%><br>
                (<%= overall_avg_position_percentage(@keywords_1, @keywords_2)%>)
            </td>
        </tr>
        <tr>
            <!-- title 2 -->
            <th>New queries</th>
            <td>
                <%= new_queries_tnk(@keywords_1, @keywords_2) %>
            </td>
            <td>
                <%= visibility_new_true(@keywords_1, @keywords_2) %><br>
                +<%= visibility_existing_true(@keywords_2) %><br>
                (<%= new_queries_visibility_percentage(@keywords_1, @keywords_2)%>)
            </td>
            <td>
                <%= traffic_new_true(@keywords_1, @keywords_2) %><br>
                Clicks<br>
                <%= traffic_existing_true(@keywords_2) %><br>
                (<%= new_queries_traffic_percentage(@keywords_1, @keywords_2) %>)
            </td>
            <td>
                <%= number_with_precision(avg_ctr_new_true(@keywords_1, @keywords_2), :precision => 2) %><br>
                +<%= number_with_precision(avg_ctr_existing_true(@keywords_2), :precision => 2) %><br>
                (<%= new_queries_avg_CTR_percentage(@keywords_1, @keywords_2) %>)
            </td>
            <td>
                <%= number_with_precision(avg_position_new_true(@keywords_1, @keywords_2), :precision => 2) %><br>
                +<%= number_with_precision(avg_positio_existing_true(@keywords_2), :precision => 2) %><br>
                (<%= new_queries_avg_position_percentage(@keywords_1, @keywords_2) %>)
            </td>
        </tr>
        <tr>
            <!-- title 3 -->
            <th>Existing queries</th>
            <td>
                <%= existing_queries_tnk(@keywords_1, @keywords_2) %>
            </td>
            <td>
                <%= visibility_new_false(@keywords_1, @keywords_2) %><br>
                +<%= visibility_existing_false(@keywords_2) %><br>
                (<%= existing_queries_percentage(@keywords_1, @keywords_2)%>)
            </td>
            <td>
                <%= traffic_new_false(@keywords_1,@keywords_2) %><br>
                Clicks<br>
                +<%= traffic_existing_false(@keywords_2)%><br>
                (<%= existing_queries_traffic_percentage(@keywords_1, @keywords_2)%>)
            </td>
            <td>
                <%= number_with_precision(avg_ctr_new_false(@keywords_1, @keywords_2), :precision => 2) %><br>
                +<%= number_with_precision(avg_ctr_existing_false(@keywords_2), :precision => 2)%><br>
                (<%= existing_queries_avg_CTR_percentage(@keywords_1, @keywords_2)%>)
            </td>
            <td>
                <%= number_with_precision(avg_position_new_false(@keywords_1, @keywords_2), :precision => 2) %><br>
                +<%= number_with_precision(avg_positio_existing_false(@keywords_2), :precision => 2)%><br>
                (<%= existing_queries_avg_position_percentage(@keywords_1, @keywords_2)%>)
            </td>
        </tr>
        </tbody>
    </table>
</div>

app/views/shared/_table_top_keywords.html.erb
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th></th>
                <th>Visibility (current)</th>
                <th>Traffic</th>
                <th>Average CTR</th>
                <th>Average Position</th>
            </tr>
        </thead>
        <tbody>
            <% top_ten_on_clicks(@keywords_1+@keywords_2).each_with_index do |val, index| %>
            <% imp, clicks, ctr, avg_position = collect_datas(val[1]) %>
            <% s_imp, s_clicks, s_ctr, s_avg_position = s_collect_datas(val[0], @keywords_2) %>
              <tr>
                <td><%= val[0] %></td>
                <td><%= imp %> <br> Impressions <br> +<%= s_imp %> <br> ( <%= compare_result(imp, s_imp) %> )</td>
                <td><%= clicks %> <br> Clicks <br> +<%= s_clicks %> <br> ( <%= compare_result(clicks, s_clicks)%> )</td>
                <td><%= ctr %> <br> +<%= s_ctr %> <br> ( <%= compare_result(ctr, s_ctr)%> )</td>
                <td><%= avg_position %> <br> +<%= s_avg_position %><br> (<%= compare_result(avg_position, s_avg_position)%>)</td>
              </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/shared/_table_top_keywords_new_impressions.html.erb
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th></th>
                <th>Visibility (current)</th>
                <th>Traffic</th>
                <th>Average CTR</th>
                <th>Average Position</th>
            </tr>
        </thead>
        <tbody>
            <% new_top_ten_on_impressions(@keywords_1).each_with_index do |val, index| %>
              <% imp, clicks, ctr, avg_position = collect_datas(val[1]) %>
              <% s_imp, s_clicks, s_ctr, s_avg_position = s_collect_datas(val[0], @keywords_2) %>
              <tr>
                <td><%= val[0] %></td>
                <td><%= imp %> <br> Impressions <br> +<%= s_imp %> <br> ( <%= compare_result(imp, s_imp) %> )</td>
                <td><%= clicks %> <br> Clicks <br> +<%= s_clicks %> <br> ( <%= compare_result(clicks, s_clicks)%> )</td>
                <td><%= ctr %> <br> +<%= s_ctr %> <br> ( <%= compare_result(ctr, s_ctr)%> )</td>
                <td><%= avg_position %> <br> +<%= s_avg_position %><br> (<%= compare_result(avg_position, s_avg_position)%>)</td>
              </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/shared/_table_top_keywords_past_impressions.html.erb
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th></th>
                <th>Visibility (current)</th>
                <th>Traffic</th>
                <th>Average CTR</th>
                <th>Average Position</th>
            </tr>
        </thead>
        <tbody>
            <% past_top_ten_on_impressions(@keywords_1).each_with_index do |val, index| %>
              <% imp, clicks, ctr, avg_position = collect_datas(val[1]) %>
              <% s_imp, s_clicks, s_ctr, s_avg_position = s_collect_datas(val[0], @keywords_2) %>
              <tr>
                <td><%= val[0] %></td>
                <td><%= imp %> <br> Impressions <br> +<%= s_imp %> <br> ( <%= compare_result(imp, s_imp) %> )</td>
                <td><%= clicks %> <br> Clicks <br> +<%= s_clicks %> <br> ( <%= compare_result(clicks, s_clicks)%> )</td>
                <td><%= ctr %> <br> +<%= s_ctr %> <br> ( <%= compare_result(ctr, s_ctr)%> )</td>
                <td><%= avg_position %> <br> +<%= s_avg_position %><br> (<%= compare_result(avg_position, s_avg_position)%>)</td>
              </tr>
            <%end%>
        </tbody>
    </table>
</div>